[package]
name = "McSrvMgr"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = {version = "1.46.1", features = ["full"]}
reqwest = {version = "0.12.22", features = ["rustls-tls"]}

[profile.release]
lto = true
codegen-units = 1
strip ="debuginfo"